### ISSUE TITLE
BLTNActionItem and BLTNPageItem reference obsolete InterfaceBuilderType

### ISSUE THREAD

**Issue by a2** [alexaubry/BulletinBoard#104]
Links to comments in [BLTNActionItem.h](https://github.com/alexaubry/BulletinBoard/blob/80eca1334270a5f167b492d1821c6cbc416571f1/Sources/Models/BLTNActionItem.h#L32-L33) and [BLTNPageItem.h](https://github.com/alexaubry/BulletinBoard/blob/80eca1334270a5f167b492d1821c6cbc416571f1/Sources/Models/BLTNPageItem.h#L25-L26)

**Comment by a2** [comment]
Seems that `interfaceBuilderType` is now a property on those classes.

**Comment by alexaubry** [comment]
@ajchili Thanks for your interest! The issue here is that we renamed a property but the comments were not updated to reflect that.

If you want to fix this, you can go in each file that @a2 mentioned, and replace 'InterfaceBuilderType' by 'interfaceBuilderType' in the comments. Make sure to follow the [contributions guide](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md) to see how you can submit your fixes.

**Comment by ajchili** [comment]
@alexaubry Thanks for the helpful feedback/advice! I'll submit a PR asap.

**Comment by alexaubry** [comment]
Fixed in #138.
