### ISSUE TITLE
Statusbar behind dimmer layer

### ISSUE THREAD

**Issue by ServusJon** [alexaubry/BulletinBoard#124]
Any chance to have the statusbar behind the dimmer layer?

**Comment by alexaubry** [comment]
You can set the `statusBarAppearance` to `hidden` on the bulletin manager before presenting if you don’t want the status bar to show over the dimming layer. 

Let me know if that works for your case.

**Comment by alexaubry** [comment]
This is not a common use case, as far as I understand. Is there anything specific you want to achieve that would require the user to not easily see the status bar?

One option could be to set the `backgroundViewStyle` to `blurred(style: UIBlurEffectStyle.dark, isDark: false)` on the manager to force the dark status bar; though this is not a recommended approach because the contrast wouldn't be enough for some visually impaired users, who need to see the status bar.

**Comment by ServusJon** [comment]
Thanks! I will just go with the blurred bar :-)
