### ISSUE TITLE
Font customization

### ISSUE THREAD

**Issue by CaliCastle** [alexaubry/BulletinBoard#18]
For appearances, there is no option to change the font of the labels which lacks of the uniform of my currently developing app and I intend to use Avenir Next throughout. This would be a nice feature to add on.

### New Issue Checklist
- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description
It would be awesome if the PageBulletinItem.interfaceFactory has a property to control the font.
More an improvement here, not an issue.

**Comment by alexaubry** [comment]
Nice idea, I'll be working on this.

**Comment by jyounus** [comment]
How about making the BulletinInterfaceFactory class "open" instead of "public"? This way we could inherit and override it to customise the properties. You'd also have to make the functions (e.g. makeTitleLabel open instead of public) for this to work, as well as change the PageBulletinItem.interfaceFactory from a let to a var property, so it can be changed.

Even better would be if you could use Protocols instead, but may not be something you want to do. It would just make it easier to override existing classes/functionality.

**Comment by CaliCastle** [comment]
@jyounus You're right, making the class open instead of "public" would a fantastic idea for better inheritance and override availability.

**Comment by alexaubry** [comment]
@jyounus Using protocols is an excellent idea. I'll work on a PR to implement this.

**Comment by alexaubry** [comment]
I've made a PR (#26) that implements a better customization API. @CaliCastle @jyounus would you mind telling me if it suits your needs?

**Comment by alexaubry** [comment]
Implemented by #26
