### ISSUE TITLE
Turn off LLVM profiling or code coverage

### ISSUE THREAD

**Issue by arkader** [alexaubry/BulletinBoard#40]
Itunes Connect issue when releasing on App Store

### New Issue Checklist

- [ ] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description
Hi Alex, 
I've got an issue with the library when I'm uploading my app on the app store.
This is the message I receive: 

Dear developer,
We have discovered one or more issues with your recent delivery for "****". To process your delivery, the following issues must be corrected:
**Invalid Bundle - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.**
Once these issues have been corrected, you can then redeliver the corrected binary.
Regards,
The App Store team

I'm not using the latest bulletin board, 
as you've changed the implementation of some functions and renaming some file,
I'm not able to upgrade to the latest version yet

Thank you! 

### Environment

- **iOS Version**: iOS 10 / iOS 11
- **Device(s)**: *

**Comment by arkader** [comment]
I've just seen that you've fixed the issue with this commit:
https://github.com/alexaubry/BulletinBoard/commit/e2b54d6a3204b9f8a03b133f4a3c98e04a918fba

How could I apply this fix to my current version?
Cheers

**Comment by alexaubry** [comment]
Hey @arkader! Sorry for the inconvenience. You seem to be using Carthage to build the framework (since CocoaPods does not enable LLVM instrumentation).

I would suggest that you update your `Cartfile` to use the commit where this issue has been fixed: 

~~~
github "alexaubry/BulletinBoard" "e2b54d6a3204b9f8a03b133f4a3c98e04a918fba"
~~~  

And then run `carthage update BulletinBoard` to build the framework without code coverage support.  No major API change were made before this commit, so rebuilding your app with this version should be fast.

 You can check if LLVM instrumentation was correctly removed by running this command: 

~~~bash
otool -l -arch all Carthage/Build/iOS/BulletinBoard.framework/BulletinBoard | grep __llvm_prf
~~~

You should not get any output if LLVM instrumentation was correctly removed.

Hope this helps!

**Comment by arkader** [comment]
Hi @alexaubry 
Thank you for you quick reply. 
I've updated the Cartfile and have runned:
`carthage update BulletinBoard` 
However, I receive few errors:
![screen shot 2017-12-08 at 14 27 10](https://user-images.githubusercontent.com/1659350/33769973-f4a1031e-dc23-11e7-8f0c-62ef9853cf9c.png)

I believe that you've made the LLVM fix after having renamed some classes.
Is there a way to cherry pick your fix and put it directly to my version?

The commit I'm using is a4fbe0c393857d2c10e5b01cc7182a4fdf361c7e

Cheers

**Comment by arkader** [comment]
I've found a way to fix the issue! 

https://stackoverflow.com/questions/46160518/xcode-9-carthage-itunes-connect-error-invalid-bundle-disallowed-llvm-instr

Thanks anyway!
