### ISSUE TITLE
actionHandler won't fire

### ISSUE THREAD

**Issue by lukaskirner** [alexaubry/BulletinBoard#79]
The actionHandler won't fire. What am I doing wrong?

- used version 1.3.0
- newest xcode
- running on ios 11.3

setupAppManager() gets called form viewDidLoad()
```
//MARK: Setup App
    private func setupAppManager() {
        let root: BulletinItem = test()
        let manager: BulletinManager = BulletinManager(rootItem: root)
        manager.prepare()
        manager.presentBulletin(above: self)
    }
    
   
    private func test() -> BulletinItem {
        let page = PageBulletinItem(title: "Foo)
        page.image = UIImage(named: "Foo")
        page.descriptionText = "Lorem Ipsum"
        page.actionButtonTitle = "Setup"
        
        // Button press interaction
        page.actionHandler = { (item: PageBulletinItem) in
            print("Pressed")
        }
        
        return page
    }
```

**Comment by alexaubry** [comment]
The bulletin manager needs to be retained by the presenting view controller. Here, you declare it inside a function, which means it will be deallocated when `setupAppManager` returns. And, when the manager is deallocated, so is the `test` bulletin item. That's why your closure isn't called (because it doesn't exist in memory anymore).

In the [README](README), I suggest that you declare the bulletin manager as a lazy variable on the presenting view controller so that it is retained. You could replace your code by:

~~~swift
lazy var manager: BulletinManager = {
    let root: BulletinItem = self.test()
    return BulletinManager(rootItem: root)
}

private func displayAppManager() {
    self.manager.prepare()
    self.manager.presentBulletin(above: self)
}
~~~ 

Let me know if it works 😄

**Comment by lukaskirner** [comment]
Worked !
@alexaubry thanks for your help
